name: pytorch-py3
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _pytorch_select=0.2
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - cairo=1.14.12
  - certifi=2019.11.28
  - cffi=1.13.1
  - chardet=3.0.4
  - cryptography=2.8
  - cudatoolkit=10.0.130
  - cudnn=7.3.1
  - cycler=0.10.0
  - dbus=1.13.12
  - decorator=4.4.1
  - defusedxml=0.6.0
  - dominate=2.4.0
  - entrypoints=0.3
  - expat=2.2.6
  - ffmpeg=4.0
  - fontconfig=2.13.0
  - freeglut=3.0.0
  - freetype=2.9.1
  - glib=2.63.1
  - graphite2=1.3.13
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - icu=58.2
  - idna=2.8
  - importlib_metadata=0.23
  - intel-openmp=2019.5
  - ipykernel=5.1.3
  - ipython=7.9.0
  - ipython_genutils=0.2.0
  - jasper=2.0.14
  - jedi=0.15.1
  - jinja2=2.10.3
  - jpeg=9c
  - json5=0.8.5
  - jsonpatch=1.24
  - jsonpointer=2.0
  - jsonschema=3.1.1
  - jupyter_client=5.3.3
  - jupyter_core=4.5.0
  - jupyterlab=1.2.1
  - jupyterlab_server=1.0.6
  - kiwisolver=1.1.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran=3.0.0
  - libgfortran-ng=7.3.0
  - libglu=9.0.0
  - libopencv=3.4.2
  - libopus=1.3
  - libpng=1.6.37
  - libprotobuf=3.10.1
  - libsodium=1.0.17
  - libstdcxx-ng=9.1.0
  - libtiff=4.0.9
  - libuuid=1.0.3
  - libvpx=1.7.0
  - libxcb=1.13
  - libxml2=2.9.9
  - markdown=3.1.1
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - mistune=0.8.4
  - mkl=2019.5
  - mkl-service=2.3.0
  - mkl_fft=1.0.14
  - mkl_random=1.1.0
  - more-itertools=7.2.0
  - nbconvert=5.6.1
  - nbformat=4.4.0
  - ncurses=6.1
  - ninja=1.9.0
  - notebook=6.0.1
  - numpy=1.17.2
  - numpy-base=1.17.2
  - olefile=0.46
  - opencv=3.4.2
  - openssl=1.1.1d
  - pandoc=2.7.3
  - pandocfilters=1.4.2
  - parso=0.5.1
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=5.4.1
  - pip=19.3.1
  - pixman=0.38.0
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.10
  - protobuf=3.10.1
  - ptyprocess=0.6.0
  - py-opencv=3.4.2
  - pycparser=2.19
  - pygments=2.4.2
  - pyopenssl=19.1.0
  - pyparsing=2.4.2
  - pyqt=5.9.2
  - pyrsistent=0.15.5
  - pysocks=1.7.1
  - python=3.7.5
  - python-dateutil=2.8.0
  - pytorch=1.2.0
  - pytorch-gpu=1.2.0
  - pytz=2019.3
  - pyzmq=18.1.0
  - qt=5.9.7
  - readline=7.0
  - requests=2.22.0
  - scipy=1.3.1
  - send2trash=1.5.0
  - setuptools=41.6.0
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.30.1
  - tensorboard=1.14.0
  - terminado=0.8.2
  - testpath=0.4.4
  - tk=8.6.10
  - torchfile=0.1.0
  - torchvision=0.4.0
  - tornado=6.0.3
  - traitlets=4.3.3
  - urllib3=1.25.7
  - visdom=0.1.8.9
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - websocket-client=0.56.0
  - werkzeug=0.16.0
  - wheel=0.33.6
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.6.9
  - xorg-libxau=1.0.9
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - zeromq=4.3.2
  - zipp=0.6.0
  - zlib=1.2.11
prefix: /Midgard/home/yipingx/miniconda3/envs/pytorch-py3

